cas-rest:
  client-rest-login-url: http://cas.app.org:18002/page/login.html

cas:
  #Required properties
  server-url-prefix: http://cas.example.org:8080/cas
#  server-login-url: http://cas.example.org:8080/cas/login
  server-login-url: http://cas.app.org:18002/page/login.html
  client-host-url: http://cas.app.org:18002

  #Optional properties
  authentication-url-patterns: [/protected, /protected2]
  validation-url-patterns: [/protected, /protected2]
  #request-wrapper-url-patterns: [/protected, /protected2]
  #assertion-thread-local-url-patterns: [/*]

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  #validation-type: SAML

  #gateway: true
  #use-session: false
  #redirect-after-validation: true
  #allowed-proxy-chains: ['https://dk.example.org:8443/proxy1', 'https://dk.example.org:8443/proxy2']
  #proxy-callback-url: https://dk.example.org:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: http://cas.app.org:18002/logout?service=http://cas.app.org:18002
#casLogoutUrl: http://cas.example.org:8080/cas/logout?service=http://cas.example.org:8080/cas

spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
server:
  port: 18002
