server:
  port: 10201
  servlet:
    context-path: /client1

spring:
  resources:
    static-locations: classpath:/css
  mvc:
    static-path-pattern: /css/**
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

security:
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
      accessTokenUri: http://localhost:10101/oauth/token
      userAuthorizationUri: http://localhost:10101/oauth/authorize
    resource:
      userInfoUri: http://localhost:10101/user