server:
  port: 10101

logging:
  level:
    org:
      springframework:
        web: INFO
    Hibernate: ERROR

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
  #    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.110.185:3306/oauth?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: learn
    password: learn-m
#    username: ENC(YiYjVwTulDGN//YaB3KbuA==) #明文root
#    password: ENC(9oaIJkFgGSDFaHH3OXY63RHWQ+amDmiJ) #明文19941017
    type: com.alibaba.druid.pool.DruidDataSource

  druid:
    initial-size: 5
    max-active: 10
    min-idle: 5
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 100000
    #spring.datasource.druid.max-evictable-idle-time-millis=
    filters: stat,wall,log4j
    web-stat-filter:
      enabled: true
      url-pattern: /*
      #      exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      session-stat-enable: true
      session-stat-max-count: 1000
      principal-session-name:
      principal-cookie-name:
      profile-enable: true
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      login-username: druid
      login-password: druid
      allow: 127.0.0.1
      deny:
    filter:
      stat:
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 2000
      wall:
        enabled: true
        db-type: mysql
        config.delete-allow: false
        config.drop-table-allow: false

  redis:
    # 101.132.110.185
    host: 101.132.110.185
    password: learn-r
    port: 16379
