server:
  port: 18444
  servlet:
    context-path: /admin
  ssl:
    enabled: false

spring:
  security:
    user:
      name: admin
      password: admin123

eureka:
  instance:
    home-page-url-path: ${server.servlet.context-path}
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator

#logging:
#  config: classpath:logback-logstash.xml

